## Travis CI Integration

notifications:
  email: false
  irc: "chat.freenode.net#d.mono-d"

language: c

install:
  - sudo deb http://ppa.launchpad.net/inizan-yannick/mono/ubuntu utopic main 
   - sudo apt-get update -q
  - sudo apt-get install mono nunit-console
 
script:
  - xbuild DParser2.Unittest.sln
  - nunit-console Tests/bin/Debug/Tests.dll