## Travis CI Integration

notifications:
  email: false
  irc: "chat.freenode.net#d.mono-d"

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild DParser2.Unittest.sln
  - nunit-console Tests/bin/Debug/Tests.dll